### ISSUE TITLE
School Suggestions #2

### ISSUE THREAD

**Issue by kaizenics** [jeoooo/PROJECTDESTINY#26]
# School Suggestions #2

- [x] Philippine College of Technology Davao
1. Landing (Main)
https://pctdavao.edu.ph/
2. Student Portal - **LINK NOT WORKING**
http://schoolms.pctdavao.edu.ph/Home/StudentLogin

~- [ ] Admin Portal
http://auth.pctdavao.edu.ph/~

- [x] Agro Industrial Foundation College of the Philippines
https://agrodavao.com/

- [x] Holy Child College of Davao - refer to #25 
https://holychild.edu.ph/

- [x]  Joji Ilagan Career Center Inc. College of Business and Tourism
https://www.jojiilagancareercenter.com/

**Comment by jeoooo** [comment]
> Admin Portal
http://auth.pctdavao.edu.ph/

@kaizenics 
website cannot be accessed 

this one will be not be added

**Comment by jeoooo** [comment]
> Student Portal
http://schoolms.pctdavao.edu.ph/Home/StudentLogin

@kaizenics 

Link does not work

**Comment by jeoooo** [comment]
@kaizenics  closed issue

please follow up on https://github.com/jeoooo/PROJECTDESTINY/issues/26#issuecomment-1953514143
