### ISSUE TITLE
School Suggestions #3

### ISSUE THREAD

**Issue by kaizenics** [jeoooo/PROJECTDESTINY#27]
Mindanao Medical Foundation College
- [x] https://mmfcdavao.com/

> Do not include the https://enroll.mmfcdavao.com.ph/start since it still part of the landing page of MMFC.

~https://enroll.mmfcdavao.com.ph/start~ 

Philippine Women's College of Davao

1. Landing:
- [x] https://pwc.edu.ph/

2. Student Portal:
- [x] http://sa.pwc.edu.ph:8339/

Samson Polytechnic College of Davao
- [x] https://samsonpcd.edu.ph/

**Comment by jeoooo** [comment]
> Mindanao Medical Foundation College
https://mmfcdavao.com/
https://enroll.mmfcdavao.com.ph/start

 @kaizenics  kindly provide description for these websites (are these landing page? student portal, etc.)

**Comment by kaizenics** [comment]
Do not include the https://enroll.mmfcdavao.com.ph/start since it still part of the landing page of MMFC.

Landing page: https://mmfcdavao.com/ 

@jeoooo

**Comment by kaizenics** [comment]
PWC Student Portal added
